apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway.yaml
  - auth.yaml
  - sender.yaml
  - parser.yaml
  - audience.yaml
  - notifier.yaml

commonLabels:
  app.kubernetes.io/part-of: email-platform
  app.kubernetes.io/managed-by: gitlab-ci
