apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: email-platform-dev

resources:
  - ../../base

images:
  - name: registry.example.com/email-platform-gateway
    newTag: latest # CI replaces with $CI_COMMIT_SHORT_SHA via `kustomize edit set image`
  - name: registry.example.com/email-platform-auth
    newTag: latest
  - name: registry.example.com/email-platform-sender
    newTag: latest
  - name: registry.example.com/email-platform-parser
    newTag: latest
  - name: registry.example.com/email-platform-audience
    newTag: latest
  - name: registry.example.com/email-platform-notifier
    newTag: latest

# Dev: 1 replica per service (default base value preserved)
